<?php
return array (
  9 => 
  array (
    'catid' => '9',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '1',
    'parentid' => '0',
    'arrparentid' => '0',
    'child' => '1',
    'arrchildid' => '9,10,11',
    'catname' => '新闻中心',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => '',
    'catdir' => 'xinwenzhonxin',
    'url' => 'http://www.hk.com/index.php?m=content&c=index&a=lists&catid=9',
    'items' => '0',
    'hits' => '0',
    'setting' => '{"workflowid":"","ishtml":"0","content_ishtml":"0","create_to_html_root":"0","template_list":"hk","category_template":"category_xingweng","list_template":"list_gonsixinwen","show_template":"show.gonsixinwen","meta_title":"","meta_keywords":"","meta_description":"","presentpoint":"1","defaultchargepoint":"0","paytype":"0","repeatchargedays":"1","category_ruleid":"6","show_ruleid":"16"}',
    'listorder' => '9',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'xinwenzhongxin',
    'usable_type' => '',
    'create_to_html_root' => '0',
    'ishtml' => '0',
    'content_ishtml' => '0',
    'category_ruleid' => '6',
    'show_ruleid' => '16',
    'workflowid' => '',
    'isdomain' => '0',
  ),
  10 => 
  array (
    'catid' => '10',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '1',
    'parentid' => '9',
    'arrparentid' => '0,9',
    'child' => '0',
    'arrchildid' => '10',
    'catname' => '公司新闻',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => 'xinwenzhonxin/',
    'catdir' => 'gonsixinwen',
    'url' => 'http://www.hk.com/index.php?m=content&c=index&a=lists&catid=10',
    'items' => '3',
    'hits' => '0',
    'setting' => '{"workflowid":"","ishtml":"0","content_ishtml":"0","create_to_html_root":"0","template_list":"hk","category_template":"category_xinwen","list_template":"list_gonsixinwen","show_template":"show.gonsixinwen","meta_title":"","meta_keywords":"","meta_description":"","presentpoint":"1","defaultchargepoint":"0","paytype":"0","repeatchargedays":"1","category_ruleid":"6","show_ruleid":"16"}',
    'listorder' => '10',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'gongsixinwen',
    'usable_type' => '',
    'create_to_html_root' => '0',
    'ishtml' => '0',
    'content_ishtml' => '0',
    'category_ruleid' => '6',
    'show_ruleid' => '16',
    'workflowid' => '',
    'isdomain' => '0',
  ),
  11 => 
  array (
    'catid' => '11',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '11',
    'parentid' => '9',
    'arrparentid' => '0,9',
    'child' => '0',
    'arrchildid' => '11',
    'catname' => '公司视频',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => 'xinwenzhonxin/',
    'catdir' => 'gonsispin',
    'url' => 'http://www.hk.com/index.php?m=content&c=index&a=lists&catid=11',
    'items' => '3',
    'hits' => '0',
    'setting' => '{"workflowid":"","ishtml":"0","content_ishtml":"0","create_to_html_root":"0","template_list":"hk","category_template":"category","list_template":"list_videos","show_template":"show_videos","meta_title":"","meta_keywords":"","meta_description":"","presentpoint":"1","defaultchargepoint":"0","paytype":"0","repeatchargedays":"1","category_ruleid":"6","show_ruleid":"16"}',
    'listorder' => '11',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'gongsishipin',
    'usable_type' => '',
    'create_to_html_root' => '0',
    'ishtml' => '0',
    'content_ishtml' => '0',
    'category_ruleid' => '6',
    'show_ruleid' => '16',
    'workflowid' => '',
    'isdomain' => '0',
  ),
  14 => 
  array (
    'catid' => '14',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '2',
    'parentid' => '0',
    'arrparentid' => '0',
    'child' => '1',
    'arrchildid' => '14,15',
    'catname' => '刊物',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => '',
    'catdir' => 'kanwu',
    'url' => 'http://www.hk.com/index.php?m=content&c=index&a=lists&catid=14',
    'items' => '0',
    'hits' => '0',
    'setting' => '{"workflowid":"","ishtml":"0","content_ishtml":"0","create_to_html_root":"0","template_list":"hk","category_template":"category_kanwu","list_template":"list_kanwu","show_template":"show_kanwu","meta_title":"","meta_keywords":"","meta_description":"","presentpoint":"1","defaultchargepoint":"0","paytype":"0","repeatchargedays":"1","category_ruleid":"6","show_ruleid":"16"}',
    'listorder' => '14',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'kanwu',
    'usable_type' => '',
    'create_to_html_root' => '0',
    'ishtml' => '0',
    'content_ishtml' => '0',
    'category_ruleid' => '6',
    'show_ruleid' => '16',
    'workflowid' => '',
    'isdomain' => '0',
  ),
  15 => 
  array (
    'catid' => '15',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '2',
    'parentid' => '14',
    'arrparentid' => '0,14',
    'child' => '0',
    'arrchildid' => '15',
    'catname' => '文化书籍',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => 'kanwu/',
    'catdir' => 'whuashuju',
    'url' => 'http://www.hk.com/index.php?m=content&c=index&a=lists&catid=15',
    'items' => '3',
    'hits' => '0',
    'setting' => '{"workflowid":"","ishtml":"0","content_ishtml":"0","create_to_html_root":"0","template_list":"hk","category_template":"category","list_template":"list_kanwu","show_template":"show_kanwu","meta_title":"","meta_keywords":"","meta_description":"","presentpoint":"1","defaultchargepoint":"0","paytype":"0","repeatchargedays":"1","category_ruleid":"6","show_ruleid":"16"}',
    'listorder' => '15',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'wenhuashuji',
    'usable_type' => '',
    'create_to_html_root' => '0',
    'ishtml' => '0',
    'content_ishtml' => '0',
    'category_ruleid' => '6',
    'show_ruleid' => '16',
    'workflowid' => '',
    'isdomain' => '0',
  ),
  16 => 
  array (
    'catid' => '16',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '1',
    'parentid' => '0',
    'arrparentid' => '0',
    'child' => '1',
    'arrchildid' => '16,17,18',
    'catname' => '关于我们',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => '',
    'catdir' => 'guanyuwomen',
    'url' => 'http://www.hk.com/index.php?m=content&c=index&a=lists&catid=16',
    'items' => '0',
    'hits' => '0',
    'setting' => '{"workflowid":"","ishtml":"0","content_ishtml":"0","create_to_html_root":"0","template_list":"hk","category_template":"category_women","list_template":"list_women","show_template":"show_women","meta_title":"","meta_keywords":"","meta_description":"","presentpoint":"1","defaultchargepoint":"0","paytype":"0","repeatchargedays":"1","category_ruleid":"6","show_ruleid":"16"}',
    'listorder' => '16',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'guanyuwomen',
    'usable_type' => '',
    'create_to_html_root' => '0',
    'ishtml' => '0',
    'content_ishtml' => '0',
    'category_ruleid' => '6',
    'show_ruleid' => '16',
    'workflowid' => '',
    'isdomain' => '0',
  ),
  17 => 
  array (
    'catid' => '17',
    'siteid' => '1',
    'type' => '1',
    'modelid' => '0',
    'parentid' => '16',
    'arrparentid' => '0,16',
    'child' => '0',
    'arrchildid' => '17',
    'catname' => '公司简介',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => 'guanyuwomen/',
    'catdir' => 'jianjie',
    'url' => 'http://www.hk.com/index.php?m=content&c=index&a=lists&catid=17',
    'items' => '0',
    'hits' => '0',
    'setting' => '{"ishtml":"0","template_list":"hk","page_template":"page_women","meta_title":"","meta_keywords":"","meta_description":"","category_ruleid":"6","show_ruleid":"","repeatchargedays":"1"}',
    'listorder' => '17',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'gongsijianjie',
    'usable_type' => '',
    'create_to_html_root' => NULL,
    'ishtml' => '0',
    'content_ishtml' => NULL,
    'category_ruleid' => '6',
    'show_ruleid' => '',
    'workflowid' => NULL,
    'isdomain' => '0',
  ),
  18 => 
  array (
    'catid' => '18',
    'siteid' => '1',
    'type' => '1',
    'modelid' => '0',
    'parentid' => '16',
    'arrparentid' => '0,16',
    'child' => '0',
    'arrchildid' => '18',
    'catname' => '核心理念',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => 'guanyuwomen/',
    'catdir' => 'lnian',
    'url' => 'http://www.hk.com/index.php?m=content&c=index&a=lists&catid=18',
    'items' => '0',
    'hits' => '0',
    'setting' => '{"ishtml":"0","template_list":"hk","page_template":"page_linian","meta_title":"","meta_keywords":"","meta_description":"","category_ruleid":"6","show_ruleid":"","repeatchargedays":"1"}',
    'listorder' => '18',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'hexinlinian',
    'usable_type' => '',
    'create_to_html_root' => NULL,
    'ishtml' => '0',
    'content_ishtml' => NULL,
    'category_ruleid' => '6',
    'show_ruleid' => '',
    'workflowid' => NULL,
    'isdomain' => '0',
  ),
  19 => 
  array (
    'catid' => '19',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '3',
    'parentid' => '0',
    'arrparentid' => '0',
    'child' => '1',
    'arrchildid' => '19,20',
    'catname' => '公司旅游',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => '',
    'catdir' => 'lvyou',
    'url' => 'http://www.hk.com/index.php?m=content&c=index&a=lists&catid=19',
    'items' => '0',
    'hits' => '0',
    'setting' => '{"workflowid":"","ishtml":"0","content_ishtml":"0","create_to_html_root":"0","template_list":"hk","category_template":"category_gonsilvyou","list_template":"list_gonsilvy","show_template":"show_gonsilvyou","meta_title":"","meta_keywords":"","meta_description":"","presentpoint":"1","defaultchargepoint":"0","paytype":"0","repeatchargedays":"1","category_ruleid":"6","show_ruleid":"16"}',
    'listorder' => '19',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'gongsilvyou',
    'usable_type' => '',
    'create_to_html_root' => '0',
    'ishtml' => '0',
    'content_ishtml' => '0',
    'category_ruleid' => '6',
    'show_ruleid' => '16',
    'workflowid' => '',
    'isdomain' => '0',
  ),
  20 => 
  array (
    'catid' => '20',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '3',
    'parentid' => '19',
    'arrparentid' => '0,19',
    'child' => '0',
    'arrchildid' => '20',
    'catname' => '我们的足迹',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => 'lvyou/',
    'catdir' => 'foot',
    'url' => 'http://www.hk.com/index.php?m=content&c=index&a=lists&catid=20',
    'items' => '2',
    'hits' => '0',
    'setting' => '{"workflowid":"","ishtml":"0","content_ishtml":"0","create_to_html_root":"0","template_list":"hk","category_template":"category","list_template":"list_gonsilvy","show_template":"show_gonsilvyou","meta_title":"","meta_keywords":"","meta_description":"","presentpoint":"1","defaultchargepoint":"0","paytype":"0","repeatchargedays":"1","category_ruleid":"6","show_ruleid":"16"}',
    'listorder' => '20',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'womendezuji',
    'usable_type' => '',
    'create_to_html_root' => '0',
    'ishtml' => '0',
    'content_ishtml' => '0',
    'category_ruleid' => '6',
    'show_ruleid' => '16',
    'workflowid' => '',
    'isdomain' => '0',
  ),
);
?>